### PR TITLE
Convert auto_logs_markup global plugin to callable tag

### PR DESCRIPTION
**Pull request by jonatack**
Now that build speed appears to no longer be an issue thanks to #154, this PR updates @harding's callable filter suggestion implemented by @jnewbery in https://github.com/bitcoin-core-review-club/bitcoin-core-review-club.github.io/tree/pr147.2

Co-authored-by: John Newbery john@johnnewbery.com
Co-authored-by: David A. Harding <dave@dtrt.org>

### CODE REVIEW

**Comment by jnewbery** [comment]
concept ACK!

**Comment by jnewbery** [comment]
This doesn't include the fix for trailing `/`s in URLs (#158). It also adds an additional newline to the end of some posts.

Are you able to fix this up so that the generated sites are identical?

**Comment by jonatack** [comment]
Rebased on master.

**Comment by jnewbery** [comment]
Rebased on master again.

**Pull request merged**
