### PR TITLE
Add meetings by PR number

### PR DESCRIPTION
**Pull request by jonatack**
Initial proposal:
- displayed in descending order
- separated by groups of PR number / 1000
- links menu placement and styling TBD

### CODE REVIEW

**Comment by jnewbery** [comment]
Thanks for this, Jon!

It seems a little inconsistent to me that for all the other indexes, the whole PR number + title is the anchor, whereas for this the PR number is the anchor and the title is plaintext. Have you tried making the PR number + title the anchor?

I also think we should remove the "<date> meeting" at the end of the line. I don't think it adds much and makes the page more cluttered.

**Comment by jonatack** [comment]
> It seems a little inconsistent to me that for all the other indexes, the whole PR number + title is the anchor, whereas for this the PR number is the anchor and the title is plaintext. Have you tried making the PR number + title the anchor?

Yes, it isn't consistent. I started with styling it like the other pages, and at the time didn't feel it was working well for this case (with no leading date), and ended up with this to see what you think. Will look at it with fresh eyes a bit later.

> I also think we should remove the " meeting" at the end of the line. I don't think it adds much and makes the page more cluttered.

I agree that it's clutter. My thought was that otherwise people might think it's the PR filing date and not the meeting date, but happy to remove it.

**Comment by jnewbery** [comment]
> I also think we should remove the " meeting" at the end of the line. I don't think it adds much and makes the page more cluttered.

Oops. I meant 'remove the `<date> meeting` from the end of the line. Github removed the thing that looked like a tag. I think there should be no date at all.

**Comment by jnewbery** [comment]
I've pushed a commit with some suggested changes to make the style more consistent with the other indexes.

**Comment by jnewbery** [comment]
... and rebased on master

**Comment by jonatack** [comment]
ACK

Subjective of course, but as a general follow-up, (I think) I'd prefer the following for all the meeting listings: 
- Only the PR number in the link tag, and the PR name in white text; this seems more calm and readable and focuses the choice of link on the PR number
- Perhaps without the `#` and `>>` as well, which seems cleaner to me

**Comment by jnewbery** [comment]
> the PR name in white text

This doesn't work for the 99% of people who have a white background :)

**Comment by jnewbery** [comment]
Thanks for the review Jon. I've squashed the commits more logically.

**Comment by jnewbery** [comment]
> as a general follow-up, (I think) I'd prefer...

Let's do this in a separate PR. I think the most important thing is for the index styles to be consistent. Now that this is merged, we can iterate on the style in a follow-up PR.

**Pull request merged**
