### PR TITLE
Add chart of coin combinations

### PR DESCRIPTION
**Pull request by amitiuttarwar**
Added an appendix section with a chart of all the possible combinations between spent, FRESH & DIRTY and some small notes on validity of combination & how the state could occur.

### CODE REVIEW

**Comment by jnewbery** [comment]
Thanks! I've made some small changes and moved the chart to above the meeting log so it's more visible.

One thing I'd suggest to make the table clearer is to add column headings (validity, spentness, freshness, dirtyness, explanation).

**Comment by amitiuttarwar** [comment]
thanks! looks good pulled above :) 

I didn't add column headings because they seem pretty self-apparent (and the first column would have to be wider and less aesthetically pleasing 😛), but I can add if you'd like.

**Comment by jnewbery** [comment]
> I didn't add column headings because they seem pretty self-apparent (and the first column would have to be wider and less aesthetically pleasing 😛), but I can add if you'd like.

ok. It was just a suggestion.

I've made another small tweak and I'll merge now.

Thanks for this contribution!

**Comment by jonatack** [comment]
Great idea, @amitiuttarwar! :100:

**Pull request merged**
