### PR TITLE
Update Ruby, Jekyll, and Gemfile dependencies

### PR DESCRIPTION
**Pull request by jonatack**
The current Ruby version 2.6.6 is no longer supported (the current EOL version is 2.7.9) -- see https://www.ruby-lang.org/en/.

- Update the specified Ruby to the current release, 3.2.2, as well as Jekyll and its dependencies to their current versions.
- Fix a `make preview` deprecation warning.

Steps to test:

- `ruby -v` to ensure Ruby 3.2.2 is installed, otherwise install it (e.g. `brew install ruby` on macOS)
- `gem update --system`
- `gem install bundler` if bundler isn't yet installed
- `bundle update --bundler`
- `bundle install` or `bundle update`
- `make preview` or `make clean preview`
- open `http://localhost:4000/` in your navigator and browse
- `rake` ("Ruby make") in another command line buffer to run the tests

### CODE REVIEW

**Review by stickies-v — APPROVED** [review]
LGTM, thanks for being on top of this @jonatack. Preview looks good to me, can't find any issues.

I also updated my bundler (`bundle update --bundler`), and am getting a slight diff in the `Gemfile.lock` which I assume is because of the new bundler - perhaps that's worth updating too while we're at it?

```
% diff Gemfile.lock Gemfile.lock.upd -C 1
*** Gemfile.lock	2023-04-26 10:57:02.000000000 +0100
--- Gemfile.lock.upd	2023-04-26 10:56:52.000000000 +0100
***************
*** 23,25 ****
      http_parser.rb (0.8.0)
!     i18n (1.12.0)
        concurrent-ruby (~> 1.0)
--- 23,25 ----
      http_parser.rb (0.8.0)
!     i18n (1.13.0)
        concurrent-ruby (~> 1.0)
***************
*** 75,80 ****
      rexml (3.2.5)
!     rouge (4.1.0)
      ruby-progressbar (1.13.0)
      safe_yaml (1.0.5)
!     sass-embedded (1.62.0)
        google-protobuf (~> 3.21)
--- 75,80 ----
      rexml (3.2.5)
!     rouge (3.30.0)
      ruby-progressbar (1.13.0)
      safe_yaml (1.0.5)
!     sass-embedded (1.58.3)
        google-protobuf (~> 3.21)
***************
*** 103,104 ****
  BUNDLED WITH
!    2.1.4
--- 103,104 ----
  BUNDLED WITH
!    2.3.25
```

**Comment by jnewbery** [comment]
I got this deprecation warning when building a preview:

```
→ make preview
## Don't do a full rebuild (to save time), but always rebuild index.html and meetings pages
rm _site/index.html || true
rm: _site/index.html: No such file or directory
rm -rf _site/meetings* || true
bundle exec jekyll serve --future --drafts --unpublished --incremental
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Configuration file: /Users/john/Code/docs/reviewclub/_config.yml
            Source: /Users/john/Code/docs/reviewclub
       Destination: /Users/john/Code/docs/reviewclub/_site
[...]
```

Fixed by updating bundler:

```
→ bundle update --bundler
Fetching gem metadata from https://rubygems.org/.
Updating bundler to 2.4.12.
Fetching bundler 2.4.12
Installing bundler 2.4.12
Using rake 13.0.6
Using public_suffix 5.0.1
Using addressable 2.8.4
[...]
→ make preview
## Don't do a full rebuild (to save time), but always rebuild index.html and meetings pages
rm _site/index.html || true
rm -rf _site/meetings* || true
bundle exec jekyll serve --future --drafts --unpublished --incremental
Configuration file: /Users/john/Code/docs/reviewclub/_config.yml
            Source: /Users/john/Code/docs/reviewclub
       Destination: /Users/john/Code/docs/reviewclub/_site
[...]
```

**Comment by stickies-v** [comment]
I don't think we necessarily need to upgrade netflify, `ruby-3.2.2` [seems](https://app.netlify.com/sites/bitcoincore-reviews/deploys/64482cdad1881800089a8136#L20) to have installed fine on the previous run.

Looks like something's wrong with the [caching](https://app.netlify.com/sites/bitcoincore-reviews/deploys/644a651ec4b99e00081d0ae4#L17), perhaps because on a subsequent run [we reverted](https://app.netlify.com/sites/bitcoincore-reviews/deploys/64497ac9e9bb7e000867f110#L15) to `ruby-2.6.6`?

**Comment by stickies-v** [comment]
@jnewbery I'd try clearing the build cache and then rerun pipeline again? https://answers.netlify.com/t/cache-issue-on-netlify/8238/2

**Pull request closed without merging**
