### PR TITLE
Add authors index

### PR DESCRIPTION
**Pull request by jonatack**
Adds a `meetings-authors` page to allow seeing PRs sorted by author. This was my motivation for this feature. It's basically a mix of the work already done for the components and hosts.

Added authors to 4 of the meetings for testing.

Handles one or multiple authors per PR.

Displays the authors in the PR layout if any are present, with links to the author's PRs and GitHub, like for meeting hosts.

### CODE REVIEW

**Comment by jnewbery** [comment]
Concept ACK. A few comments:

- the PR layout is a bit busy now with all of the additional metadata:
  image
  I suggest we try to tidy it up a bit before merging this.
- We should add authors to all existing PRs
- I've been thinking of writing a small script to help create new pages, rather than having to manually fill in all the metadata. The script would use the github API to fill in the page variables. That'd be even more useful if we add author as a page property.

**Comment by jonatack** [comment]
Agreed.

I wrote a command line task to create new posts. It used GitHub's current v4 GraphQL API which inconveniently requires an OAuth token, so I changed it to call GitHub's older v3 REST API.  Will push it later today.

**Comment by jonatack** [comment]
Will finish this after #78 is merged.

**Comment by jonatack** [comment]
Rebased and updated.

> Concept ACK
> 
>     * the PR layout is a bit busy now with all of the additional metadata
>       I suggest we try to tidy it up a bit before merging this.
Done.

>     * We should add authors to all existing PRs
Done.

**Comment by jnewbery** [comment]
ACK 8e240138ecea2a31519e59da704e681db9415834. Looks great. Thanks Jon!

**Pull request merged**
