### PR TITLE
layout: include time and place on PR page

### PR DESCRIPTION
**Pull request by pinheadmz**
I sent this week's meeting link to some coworkers, they asked me how to join the meeting!
This PR adds the where & when to each meeting page:

#### Current

Screen Shot 2019-12-09 at 10 13 44 AM

#### Updated

Screen Shot 2019-12-09 at 10 13 38 AM

### CODE REVIEW

**Comment by jonatack** [comment]
Thanks @pinheadmz! Concept ACK but I think it should be displayed for upcoming meetings only, as (a) the information can change and be no longer valid, e.g. the meeting time changed recently, and (b) those details might be less relevant for meetings that have already taken place. WDYT?

**Comment by jnewbery** [comment]
Thanks @pinheadmz ! Your coworkers aren't the only people to have been confused by this, so concept ACK.

Rather than duplicate the meeting time/location in `_layouts/pr.html`, we should move them to site settings so that if they need to be changed in future, we just change them in one place. I've done that in https://github.com/bitcoin-core-review-club/bitcoin-core-review-club.github.io/pull/89. Can you take a look, and if you agree, then make this PR using site settings on top of that PR?

**Comment by jonatack** [comment]
+1 on de-duplicating but "Dec 11, 2019 at 18:00 on Wednesday" seems a bit awkward. Might need to have more granular control than #89 or find something that works in both.

**Comment by pinheadmz** [comment]
Yeah, this could be a lot smarter... brb

**Comment by jonatack** [comment]
Can display it only for upcoming meetings with:
```html
{% capture nowunix %}{{'now' | date: "%s"}}{% endcapture %}
{% capture posttime %}{{page.date | date: '%s'}}{% endcapture %}

{% capture components %}
  {%- for comp in page.components -%}
    <a href="/meetings-components/#{{comp}}">{{comp}}</a>{% unless forloop.last %}, {% endunless %}
  {%- endfor -%}
{% endcapture %}

<section>
  <div class="post-content">
    <h1>{{ page.title }} ({{components}})</h1>
    <time class="dt-published" datetime="{{ page.date | date_to_xmlschema }}">
      {%- assign date_format = site.minima.date_format | default: "%b %-d, %Y" -%}
      {{ page.date | date: date_format }}
      {% if posttime >= nowunix %}
        at 18:00 UTC on the #bitcoin-core-pr-reviews IRC channel
      {%- endif -%}
    </time>   
```

**Comment by jnewbery** [comment]
> "Dec 11, 2019 at 18:00 on Wednesday" seems a bit awkward

Agree. Could update the site settings to have `irc_meeting_day` and `irc_meeting_time`?

**Comment by pinheadmz** [comment]
Updated, but relies on #89 and rebase on master.
Time and place only displayed on upcoming meetings, like so:

Screen Shot 2019-12-10 at 1 14 36 PM

**Comment by jnewbery** [comment]
Thanks @pinheadmz. Looks good. I've rebased this on #89 rebased on master.

**Comment by jonatack** [comment]
Thanks @pinheadmz and @jnewbery, looks great.

**Pull request merged**
