### PR TITLE
fuzz

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by jnewbery** [comment]
Made a few small modifications (lowercase "tests", move a note about running fuzzers from the questions to the notes).

Let me know if you're happy with that and I'll merge.

**Comment by MarcoFalke** [comment]
Modified you modification ;)

**Comment by jnewbery** [comment]
squashed

**Comment by jnewbery** [comment]
Thanks @MarcoFalke . I'm going to learn a lot in this one :heart:

**Pull request merged**
