### PR TITLE
Add onboarding blog post

### PR DESCRIPTION
**Pull request by amitiuttarwar**

### CODE REVIEW

**Comment by jonatack** [comment]
Two thoughts:

- I'm not sure there needs to be more articles listed. (I've been writing detailed articles about onboarding for almost a year now -- https://jonatack.github.io/articles -- but didn't think it necessary to add them here because the two articles already listed are really good.)

- One of the things that makes the Song article outstanding is that it clearly recommends to begin by reviewing and testing, and not by opening PRs. The article this PR proposes to add, while enjoyable and interesting as a personal account, reinforces the idea for new people that contributing = opening PRs. From the PoV of Bitcoin, I'm not sure that's ideal. This is a change I'd suggest if you are open to edits. That said, I'm pretty close to giving up on the message about the importance of review (now that I've written a fair amount about it) and moving on to other topics ;)

**Comment by jonatack** [comment]
In other words, you have a position of influence, a sustainable place in the ecosystem, a lot of support, and your article is being celebrated; please consider using that to promote review and testing.

**Comment by jonatack** [comment]
For better or worse, people ask me about getting started.

In response, I reply with the message of Song & Newbery, which is basically *"begin with testing and reviewing, and being sure to do much more of that than opening PRs. Song says a ratio of 3:1; Newbery 5 to 15:1."* I suggest the latter to people and then point them to my articles.

But that's not what people want to hear. What they *really* want to hear is one of:

*a) it's good to participate in the review club to learn, as a stepping stone to the real stuff of opening PRs*

or

*b) reviewing and testing is hard and can't realistically be done by newer contributors; it's good to learn a bit about it to help with opening PRs, but it should really be left to the experienced developers*

So when they come across information that supports one of these viewpoints, they tell me about it and push back. That is what has been happening anew since Friday. I hope that helps explain what I meant above.

**Comment by jonatack** [comment]
(To clarify what I meant above:)

For better or worse, a fair amount of new people ask me about getting started. In response, I generally reply with the message of Song & Newbery, which in part is:

*"begin with testing and reviewing, and be sure to do much more of that than opening PRs. Song says a ratio of 3:1; Newbery 5 to 15:1."*

I suggest the latter to people and then point them to my articles.

But! -- that's not what people want to hear. What they *really* want to hear is one of:

*a) it's good to participate in the review club to learn, as a stepping stone to the real stuff of opening PRs*

or

*b) reviewing and testing is hard and can't realistically be done by newer contributors; it's good to learn a bit about it to help with opening PRs, but it should really be left to the experienced developers*

So when they come across information that supports one of these viewpoints, they tell me about it and push back. That is what has been happening anew since Friday. I hope that helps explain what I meant above. Best.

**Comment by jnewbery** [comment]
Thanks for the PR @amitiuttarwar and the comments @jonatack . I've added a link to this post in #127.

**Pull request closed without merging**
