### PR TITLE
Pr147.1

### PR DESCRIPTION
**Pull request by jnewbery**
A few changes to #147. Opening as a PR so it's easy to see a netlify preview. The changes here can be taken in #147 if @jonatack likes them.

### CODE REVIEW

**Comment by jnewbery** [comment]
A few changes from the original PR that I think are nice:

- line number is clickable to get a link to that line
- background highlighting works as you'd expect when the line is targeted
- line numbers are unselectable, so users can copy-paste sections of the log without including the line numbers
- logs are html-escaped (take a look at line 255 here: https://deploy-preview-147--bitcoincore-reviews.netlify.com/17428.html to see why that's required)

**Comment by jonatack** [comment]
Excellent!

Some suggested changes after testing:
```diff
diff --git a/_plugins/auto_logs_markup.rb b/_plugins/auto_logs_markup.rb
index 15d7527..7d16484 100644
--- a/_plugins/auto_logs_markup.rb
+++ b/_plugins/auto_logs_markup.rb
@@ -3,7 +3,6 @@
 # Convert plain text log into HTML markup with line number links.
 Jekyll::Hooks.register :documents, :pre_render do |post|
   # Regex to select lines that begin with HH:MM time.
-  # post.content.partition("Meeting Log").last.gsub!(/^([0-1][0-9]|[2][0-3]):[0-5][0-9] .*/).with_index(1) do |line, index|
   post.content.gsub!(/^([0-1][0-9]|[2][0-3]):[0-5][0-9] .*/).with_index(1) do |line, index|
     # Separate the log line into individual parts.
     lineno  = "#{'&nbsp;' * (4 - index.to_s.length)}#{index}"
@@ -11,10 +10,15 @@ Jekyll::Hooks.register :documents, :pre_render do |post|
     nick    = /<.+?>/.match(line).to_s.gsub(/[<>]/, '').strip
     message = CGI.escapeHTML(line[6..-1].sub(/<.+?>/, ''))
     # Return the log line in HTML markup version.
-    "<table class=\"log-line\" id=\"l-#{index}\"><tr class=\"log-row\">" \
-      "<td class=\"log-lineno\"><a href=\"#l-#{index}\">#{lineno}</a></td>" \
-      "<td class=\"log-time\">#{time}</td>" \
-      "<td><span class=\"log-nick\">&lt;#{nick}&gt;</span>" \
-      "<span class=\"log-msg\">#{message}</span></td></tr></table>"
+    "<table class='log-line' id='l-#{index}'>" \
+      "<tr class='log-row'>" \
+        "<td class='log-lineno'><a href='#l-#{index}'>#{lineno}</a></td>" \
+        "<td class='log-time'>#{time}</td>" \
+        "<td>" \
+          "<span class='log-nick'>&lt;#{nick}&gt;</span>" \
+          "<span class='log-msg'>#{message}</span>" \
+        "</td>" \
+      "</tr>" \
+    "</table>"
   end
 end
diff --git a/assets/css/all.sass b/assets/css/all.sass
index 932d742..75b646a 100644
--- a/assets/css/all.sass
+++ b/assets/css/all.sass
@@ -82,13 +82,18 @@ a
   \:target
     background-color: #ddd
   a
-    color: #5f5f5f
+    color: grey
     text-decoration: none
     user-select: none
 
 .log-time
   color: blue
+  padding-left: 6px
+  padding-right: 6px
 
 .log-nick
   font-weight: bold
   color: green
+
+.log-msg
+  padding-left: 0px
```

**Comment by jonatack** [comment]
I'll put it all together in the PR and add a commit to remove all the ```.

**Comment by jnewbery** [comment]
> Some suggested changes after testing

These all look good. Thanks!

Closing this now that you've taken the changes into #147

**Pull request closed without merging**
