### PR TITLE
n16202: add p2p encryption core dev transcript

### PR DESCRIPTION
**Pull request by jonatack**
and (perhaps controversially) update an imprecise answer of mine to not send people looking in the wrong place.

### CODE REVIEW

**Comment by jnewbery** [comment]
Good idea to add the link to the transcript, but I don't think we should be changing the transcripts after the fact. Can you remove that part of the commit?

**Comment by jnewbery** [comment]
Feel free to add a **corrections** section at the end.

**Comment by jonatack** [comment]
Good idea @jnewbery, thanks!

**Comment by jnewbery** [comment]
Looks great. Thanks for your diligence 😁

**Pull request merged**
