### PR TITLE
Fix vertical alignment of PRs

### LINKED ISSUE #27: Listings improvements
From @jonatack (https://github.com/bitcoin-core-review-club/bitcoin-core-review-club.github.io/pull/21#issuecomment-535686932)

A couple of future ideas:

- Add the host link to the listings, along with column headers Date / Host / PR.
- To make the variable width of the date columns not mess up vertical alignment (noticeable in the new [previous meetings page](https://bitcoin-core-review-club.github.io/previous_meetings.html)), adopt a fixed-width font or use an HTML table or similar markup.

### PR DESCRIPTION
**Pull request by jnewbery**
Close #27

### CODE REVIEW

**Comment by jnewbery** [comment]
Thanks for the review Jon. I'll address feedback once the pre-requisite PRs are merged.

**Comment by jnewbery** [comment]
Thanks for the review @jonatack 

> I wonder if the new month/year separaters distract from the content a bit and could be smaller (e.g. the same size as the content) or removed.

I've changed the styling a bit (reduced vertical padding for months, changed color to grey, added left padding for tables). See if you think it's more legible now.

> Some markup indentation seems lost or harder to read,

Fixed

**Comment by jnewbery** [comment]
Latest push updates all indexes to use the same style. Can probably rename the `month` class style and just included it directly in the index layout for h3 elements, but looking for concept feedback first.

**Comment by jonatack** [comment]
Thanks @jnewbery. Made review comments and proposed suggestions in #86.

**Comment by jnewbery** [comment]
Thanks Jon. I've taken your commits from #86 and added a couple more:

- apply the HTML fixups to the index page
- vertical-align the date and arrows to top (so they're aligned with the top line of the meeting title)

**Comment by jonatack** [comment]
ACK be8a2d6fdeba01430772c610bc41387f1a1a33d8, nice improvements!

**Pull request merged**
